/**
 * utils/image-studio-templates-2610.ts: 이미지 스튜디오 템플릿 2026-10-04 확장분 중 신설 카테고리 3종 (56)
 *
 * 고객사 = 뷰티 · 의류 · 요식업(Harold 2026-10-04). 이번 확장 200종은 이 세 업종에만 맞췄다.
 *   - 외식·메뉴(제품): 식당 메뉴 사진. 카페·음료와 신메뉴·팝에 없던 식사 메뉴 축
 *   - 안내·예약 · 모집·참여(행사): 예약 · 포장 · 메뉴 개편 · 체험단 · 리뷰 등 세 업종 공통 고지와 모집
 * 왜 따로 두나: 신설 카테고리는 전부 새것이라 배열 안 순서가 무관하다. 한 파일로 떼어 두면 리뷰와 일괄 치환 사고가 이 안에서 끝난다.
 * 기존 카테고리 보강분(뷰티 · 패션 · 세일·이벤트 · 카페·음료 · 신메뉴·팝 · 멤버십)은 image-studio-templates.ts 안 각 카테고리 첫 항목 앞에 있다.
 * 규약 = docs/FEATURE-IMAGE-STUDIO.md §4 (데이터만 · 숫자 채우기 금지 · 고객 노출 문자열에 금액·혜택 약속 0).
 * 행사 템플릿은 화면이 문구 위치 '위'를 기본으로 보내므로 장면이 위쪽 1/3을 비운다.
 * 영업 업종표(sales-outreach-produce INDUSTRY_TEMPLATE_MAP): 외식·메뉴 = food 제품 풀에 연결(Harold 2026-10-05). 영업 포스터는 문구를 위에 조립하므로
 *   외식·메뉴는 전부 위쪽 1/3을 비우는 구도다. 안내·예약 · 모집·참여는 잇지 않았다.
 */
import type { StudioTemplate } from './image-studio-templates';

export const TEMPLATES_2610: StudioTemplate[] = [
  // ══ 외식·메뉴 (30 · 제품 · 2026-10-04 신설) ══
  {
    id: 'food-steam-bowl', name: '김 오르는 한 그릇', category: '외식·메뉴',
    desc: '뜨거운 국물에서 피어오르는 김 클로즈업', accent: '#8b5a3c',
    useCase: '국·탕·면 등 따뜻한 한 그릇 메뉴·간편식',
    scaffold: 'A close-up of a steaming ceramic bowl of hot broth on a dark slate table, thick curls of steam rising and catching soft side light, a pair of wooden chopsticks on a rest, a few scattered green onions. The product stands beside the bowl. The upper third is dark softly blurred background where the steam fades out. Appetizing, moody food photography.',
    textStyle: 'Warm hearty typography in cream on the dark upper background, small uppercase label and a bold rounded headline.',
    defaultTexts: { label: 'HOT & HEARTY', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '김이 오를 때 한 숟갈', subtitle: '따끈한 한 그릇' },
  },
  {
    id: 'food-cross-section', name: '단면 컷', category: '외식·메뉴',
    desc: '층층이 보이는 단면을 정면에서', accent: '#e0a96d',
    useCase: '김밥·샌드위치·떡 등 단면이 예쁜 식품',
    scaffold: 'A clean cross-section of layered food sliced straight through, shown front-on on a light wooden board: distinct colorful layers, sharp knife-cut edges, a few slices fanned out, bright crisp studio light with a soft shadow. The product stands to one side of the board. The upper third is a plain warm beige backdrop. Precise, appetizing studio food photography.',
    textStyle: 'Bold appetizing typography in deep tomato red on the plain upper backdrop, small uppercase label and a chunky headline.',
    defaultTexts: { label: 'INSIDE', title: '{productName}', subtitle: '' },
    sample: { title: '잘라 보면 알아요', subtitle: '꽉 찬 단면' },
  },
  {
    id: 'food-sauce-pour', name: '소스 붓는 순간', category: '외식·메뉴',
    desc: '윤기 나는 소스가 쏟아지는 찰나', accent: '#7c2e1e',
    useCase: '소스·양념·드레싱 등 붓는 식품',
    scaffold: 'A freeze-motion moment of glossy sauce pouring in from the right side onto a dish, a smooth ribbon of liquid with a few splashes suspended in the air, black background, crisp high-speed flash lighting with bright specular highlights. The product stands beside the dish. The upper third is clean black space. Dramatic, appetizing studio photography.',
    textStyle: 'Bold glossy typography in warm cream on the black upper area, small uppercase label and a heavy headline.',
    defaultTexts: { label: 'POUR', title: '{productName}', subtitle: '' },
    sample: { title: '부어야 완성되는 맛', subtitle: '소스 한 줄기' },
  },
  {
    id: 'food-banchan-topdown', name: '한상 차림', category: '외식·메뉴',
    desc: '작은 반찬 그릇이 가득한 한상 탑다운', accent: '#b5543c',
    useCase: '반찬·한식 간편식·도시락 반찬',
    scaffold: 'A top-down view of a traditional Korean table spread: many small ceramic dishes of colorful side dishes, a bowl of rice and soup, brass spoon and chopsticks, a natural wood table, soft even daylight. The product sits among the dishes near the center. The upper band of the frame is bare wood tabletop. Generous, homely Korean food photography.',
    textStyle: 'Warm traditional-feeling typography in deep red brown on the bare upper tabletop, small label and a bold headline.',
    defaultTexts: { label: 'HANSANG', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '한 상 가득 차린 날', subtitle: '집밥의 반찬' },
  },
  {
    id: 'food-bento-grid', name: '도시락 칸', category: '외식·메뉴',
    desc: '칸칸이 채운 도시락 탑다운', accent: '#f0c75e',
    useCase: '도시락·간편식·소분 식품',
    scaffold: 'A top-down view of a bento box with neat compartments filled with colorful food in a crisp grid, chopsticks laid alongside, on a pale blue cloth, bright clean daylight. The box fills the lower two thirds and the product sits next to it. The upper third of the frame is plain cloth kept empty for the headline. Cheerful, orderly lunch photography.',
    textStyle: 'Cheerful rounded typography in deep blue on the plain cloth in the upper third, small label above a bold headline.',
    defaultTexts: { label: 'LUNCH BOX', title: '{productName}', subtitle: '' },
    sample: { title: '칸칸이 채운 점심', subtitle: '도시락 메뉴' },
  },
  {
    id: 'food-grill-flame', name: '그릴 불맛', category: '외식·메뉴',
    desc: '불꽃과 그을린 자국의 그릴', accent: '#3a2a24',
    useCase: '육류·구이·바비큐 소스',
    scaffold: 'A grill with live flames leaping between iron grates, fresh char marks on the food, drifting smoke, dark background, warm orange rim light from the fire. The product stands on a wooden board beside the grill. The upper third is dark smoky space. Bold, smoky, appetite-driving photography.',
    textStyle: 'Strong fiery typography in warm white on the dark smoky upper area, small uppercase label and a heavy condensed headline.',
    defaultTexts: { label: 'GRILLED', title: '{productName}', subtitle: '' },
    sample: { title: '불맛이 살아 있는', subtitle: '구워야 맛있는' },
  },
  {
    id: 'food-delivery-bag', name: '배달 도착', category: '외식·메뉴',
    desc: '현관 앞에 막 도착한 배달 봉투', accent: '#e07a3f',
    useCase: '배달 메뉴·포장 음식',
    scaffold: 'A food delivery just arrived at an apartment door: an insulated delivery bag and a paper bag with no printing set on the doormat, warm hallway light, a faint wisp of steam escaping from the bag. The product sits beside the bags. The upper third is the plain door surface. Cozy, anticipatory evening photography.',
    textStyle: 'Friendly bold typography in warm white on the plain door area at the top, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'DELIVERED', title: '{productName}', subtitle: '' },
    sample: { title: '문 앞에 도착한 저녁', subtitle: '배달 메뉴' },
  },
  {
    id: 'food-spice-macro', name: '양념 매크로', category: '외식·메뉴',
    desc: '고춧가루와 깨알을 아주 가까이', accent: '#b8402a',
    useCase: '양념·향신료·가루 식품',
    scaffold: 'An extreme macro of spices and seeds in small heaps: coarse red pepper flakes, sesame seeds and peppercorns, every grain sharp, warm raking light, shallow depth of field. The product rests small near the lower edge. The upper area is a smooth blurred warm tone. Tactile, intense macro food photography.',
    textStyle: 'Compact strong typography in cream placed small in the upper corner, thin uppercase label with a compact headline, never covering the spices.',
    defaultTexts: { label: 'SPICE', title: '{productName}', subtitle: '' },
    sample: { title: '알갱이까지 살아 있는', subtitle: '양념의 결' },
  },
  {
    id: 'dine-chef-pass', name: '셰프 패스', category: '외식·메뉴',
    desc: '열등 아래 막 나가는 접시들', accent: '#c1440e',
    useCase: '셰프 추천·코스 요리 메뉴',
    scaffold: 'A restaurant kitchen pass under warm heat lamps with several freshly plated dishes lined up ready to go, a pair of plating tweezers resting on the steel counter, gleaming stainless surfaces, no people and no order tickets. The product sits at the front of the pass. The upper third is the warm glow of the lamps fading into dark. Professional, behind-the-scenes restaurant photography.',
    textStyle: 'Confident warm typography in cream on the dark upper area, small uppercase label and a bold headline.',
    defaultTexts: { label: 'CHEF PICK', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '주방에서 막 나온 접시', subtitle: '셰프 추천' },
  },
  {
    id: 'dine-noodle-lift', name: '면 끌어올리기', category: '외식·메뉴',
    desc: '김 오르는 그릇에서 들어 올린 면발', accent: '#e9a23b',
    useCase: '면·국수·라면 메뉴',
    scaffold: 'A pair of chopsticks lifting a glossy bundle of noodles high above a steaming bowl of broth, the hand out of frame, droplets falling back into the bowl, warm side light through the steam, dark background. The product sits beside the bowl. The upper third is dark space with soft rising steam. Appetizing, dynamic noodle photography.',
    textStyle: 'Appetizing bold typography in warm cream on the dark upper area, small uppercase label and a rounded heavy headline.',
    defaultTexts: { label: 'NOODLE', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '후루룩 한 젓가락', subtitle: '면 요리' },
  },
  {
    id: 'dine-sizzle-plate', name: '지글지글 철판', category: '외식·메뉴',
    desc: '연기 오르는 뜨거운 철판 요리', accent: '#5c3d2e',
    useCase: '철판·스테이크·볶음 메뉴',
    scaffold: 'A cast iron sizzling plate on a wooden board with sauce bubbling and splattering, thick steam and smoke curling up, warm amber backlight catching every droplet, dark rustic table. The product sits beside the board. The upper third is dark smoky space. Hot, sizzling, crave-worthy food photography.',
    textStyle: 'Hot bold typography in warm white on the dark upper smoke, small uppercase label and a heavy condensed headline.',
    defaultTexts: { label: 'SIZZLING', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '소리부터 맛있는', subtitle: '철판 메뉴' },
  },
  {
    id: 'dine-hotpot', name: '보글보글 전골', category: '외식·메뉴',
    desc: '버너 위에서 끓는 전골 냄비', accent: '#b23a48',
    useCase: '전골·찌개·탕 등 끓여 먹는 메뉴',
    scaffold: 'A wide shallow hot pot bubbling vigorously on a tabletop burner, colorful ingredients arranged in sections, rising steam, small side dishes around it, warm cozy restaurant light. The product sits beside the pot. The upper third is warm blurred restaurant background. Cozy, sharing-table food photography.',
    textStyle: 'Cozy hearty typography in cream on the warm blurred upper background, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'HOT POT', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '보글보글 끓을 때', subtitle: '전골 메뉴' },
  },
  {
    id: 'dine-omakase', name: '오마카세 카운터', category: '외식·메뉴',
    desc: '편백 카운터 위 한 점의 초밥', accent: '#d9c8a9',
    useCase: '오마카세·스시·일식 코스',
    scaffold: 'A pale hinoki wood counter with a single piece of sushi on a small ceramic plate, a folded hand towel and a ceramic cup of tea beside it, soft focused light from above, calm minimal restraint. No people. The product sits at the end of the counter. The upper third is a softly blurred warm wall. Refined, minimal Japanese dining photography.',
    textStyle: 'Refined minimal typography in deep charcoal on the upper wall, small spaced label and a serif-feeling headline.',
    defaultTexts: { label: 'OMAKASE', title: '{productName}', subtitle: '' },
    sample: { title: '오늘의 한 점', subtitle: '오마카세' },
  },
  {
    id: 'dine-pizza-pull', name: '피자 치즈 늘어짐', category: '외식·메뉴',
    desc: '들어 올린 조각에서 길게 늘어나는 치즈', accent: '#f4a259',
    useCase: '피자·치즈가 핵심인 메뉴',
    scaffold: 'A slice of pizza being lifted from a whole pie with long strings of melted cheese stretching down, blistered crust, a few basil leaves, warm wood-fired oven glow in the background. The product sits beside the pizza board. The upper third is the soft dark oven background. Irresistible, cheesy food photography.',
    textStyle: 'Bold playful typography in warm cream on the dark upper area, small uppercase label and a chunky headline.',
    defaultTexts: { label: 'CHEESE PULL', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '치즈가 끝없이', subtitle: '피자 메뉴' },
  },
  {
    id: 'dine-fried-crunch', name: '바삭 튀김', category: '외식·메뉴',
    desc: '부스러기가 튀는 바삭한 치킨', accent: '#d4a017',
    useCase: '치킨·튀김 메뉴',
    scaffold: 'A pile of golden fried chicken on a parchment-lined tray with a few crumbs flying off a just-broken crispy piece, crisp high-speed light, a small dish of sauce, a dark warm background. The product sits beside the tray. The upper third is dark warm space. Crunchy, crave-worthy food photography.',
    textStyle: 'Crunchy heavy typography in warm white on the dark upper area, small uppercase label and a bold headline.',
    defaultTexts: { label: 'CRISPY', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '바삭, 소리부터 다른', subtitle: '튀김 메뉴' },
  },
  {
    id: 'dine-dumpling-steamer', name: '찜기 만두', category: '외식·메뉴',
    desc: '뚜껑을 연 대나무 찜기와 김', accent: '#c9b79c',
    useCase: '만두·딤섬 등 찜 메뉴',
    scaffold: 'Stacked bamboo steamers with the top lid lifted, a burst of steam rising over plump dumplings inside, a small dish of dipping sauce, warm soft light on a dark wooden table. The product sits beside the steamers. The upper third is dark space with drifting steam. Comforting, steaming food photography.',
    textStyle: 'Comforting warm typography in cream on the dark upper area, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'STEAMED', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '뚜껑을 열면 김이', subtitle: '찜 메뉴' },
  },
  {
    id: 'dine-ramen-topdown', name: '라멘 탑다운', category: '외식·메뉴',
    desc: '고명을 가지런히 올린 라멘 위에서', accent: '#a44a3f',
    useCase: '라멘·쌀국수 등 고명이 예쁜 면 메뉴',
    scaffold: 'A top-down view of a ramen bowl with toppings neatly arranged in sections over rich broth, a halved egg, sliced meat, scallions and seaweed, a black ceramic bowl on a dark wooden table, soft overhead light. The product sits beside the bowl. The upper band is bare dark wood. Orderly, appetizing overhead food photography.',
    textStyle: 'Appetizing clean typography in warm cream on the bare upper band, small uppercase label and a bold headline.',
    defaultTexts: { label: 'RAMEN', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '고명까지 가지런히', subtitle: '라멘' },
  },
  {
    id: 'dine-dining-room', name: '다이닝 룸', category: '외식·메뉴',
    desc: '영업 전 세팅을 마친 식당 홀', accent: '#8c5e3c',
    useCase: '매장 분위기·홀 이용 안내',
    scaffold: 'A restaurant dining room before service: neatly set tables with folded napkins and glasses, warm pendant lights glowing, polished wooden floor, a calm waiting atmosphere. No people. The product sits on the nearest table. The upper third is the softly lit ceiling area. Inviting, atmospheric restaurant interior photography.',
    textStyle: 'Inviting warm typography in cream on the upper ceiling area, small uppercase label and a serif-feeling headline.',
    defaultTexts: { label: 'DINING', title: '{productName}', subtitle: '' },
    sample: { title: '자리를 준비했어요', subtitle: '매장 안내' },
  },
  {
    id: 'dine-pairing-dinner', name: '페어링 디너', category: '외식·메뉴',
    desc: '촛불과 잔이 놓인 코스 한 접시', accent: '#4a1c2a',
    useCase: '코스·페어링 디너 메뉴',
    scaffold: 'An intimate dinner table with candlelight, two stemmed glasses and a beautifully plated course on a white plate, a linen napkin, dark moody background. No people. The product sits beside the plate. The upper third is dark candlelit space. Romantic, fine dining photography.',
    textStyle: 'Romantic elegant typography in soft gold on the dark upper area, small spaced label and a serif-feeling headline.',
    defaultTexts: { label: 'DINNER', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '천천히 즐기는 저녁', subtitle: '디너 코스' },
  },
  {
    id: 'dine-lunch-tray', name: '점심 정식 트레이', category: '외식·메뉴',
    desc: '밥과 국과 반찬을 담은 정식 쟁반', accent: '#d08c60',
    useCase: '점심 정식·백반 메뉴',
    scaffold: 'A lunch set on a wooden tray: a bowl of rice, a bowl of soup, several small side dishes and a main dish, spoon and chopsticks laid neatly, bright midday light from a restaurant window. The product sits next to the tray. The upper third is the soft bright window area. Honest, satisfying lunch photography.',
    textStyle: 'Friendly bold typography in deep brown on the bright upper area, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'LUNCH', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '든든한 점심 한 상', subtitle: '점심 정식' },
  },
  {
    id: 'dine-private-room', name: '프라이빗 룸', category: '외식·메뉴',
    desc: '원형 회전판이 있는 단독 룸', accent: '#7d4e57',
    useCase: '단체·모임·룸 예약 안내',
    scaffold: 'A private dining room with a large round table and a lazy susan set for a group, upholstered chairs, warm wall sconces and a decorative screen, calm and exclusive. No people. The product sits on the lazy susan. The upper third is the softly lit wall. Exclusive, group-dining interior photography.',
    textStyle: 'Exclusive warm typography in cream on the upper wall, small uppercase label and a serif-feeling headline.',
    defaultTexts: { label: 'PRIVATE ROOM', title: '{productName}', subtitle: '' },
    sample: { title: '모임은 룸에서', subtitle: '단체 예약' },
  },
  {
    id: 'dine-wok-fire', name: '불 맛 웍', category: '외식·메뉴',
    desc: '불꽃 위로 튀어 오르는 웍 요리', accent: '#e85d04',
    useCase: '볶음·중식·불 맛 메뉴',
    scaffold: 'A wok tossed over a roaring burner with tall orange flames, ingredients flying up in a glossy arc, the cook out of frame, a dark open kitchen behind. The product sits on the steel counter in front. The upper third is dark kitchen space with flame glow. Fiery, energetic kitchen photography.',
    textStyle: 'Fiery bold typography in warm white on the dark upper area, small uppercase label and a heavy headline.',
    defaultTexts: { label: 'WOK HEI', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '불 맛이 다른 이유', subtitle: '볶음 메뉴' },
  },
  {
    id: 'dine-pocha-night', name: '포차 네온', category: '외식·메뉴',
    desc: '네온 아래 플라스틱 의자의 야간 포차', accent: '#ff006e',
    useCase: '야식·포차·심야 영업 메뉴',
    scaffold: 'A late-night street pub tent glowing under pink and orange neon, plastic stools around a small table with steaming dishes, a wet street reflecting the lights, lively night mood. No people and no readable signs. The product sits on the table. The upper third is dark night with soft neon glow. Lively, late-night food photography.',
    textStyle: 'Lively neon-feeling typography in white on the dark upper night, small uppercase label and a heavy headline.',
    defaultTexts: { label: 'LATE NIGHT', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '오늘 밤 한 잔 곁들여', subtitle: '심야 메뉴' },
  },
  {
    id: 'dine-kids-plate', name: '키즈 메뉴', category: '외식·메뉴',
    desc: '모양 낸 음식이 담긴 알록달록 접시', accent: '#ffb4a2',
    useCase: '어린이 메뉴·가족 메뉴',
    scaffold: 'A colorful divided kids plate with playfully shaped food, small fruit pieces, a little cup and child-size cutlery on a bright table, cheerful daylight. No people. The product sits beside the plate. The upper third is a plain cheerful wall. Fun, family-friendly food photography.',
    textStyle: 'Fun rounded typography in deep coral on the upper wall, small label and a bouncy headline.',
    defaultTexts: { label: 'KIDS MENU', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '아이도 좋아하는 접시', subtitle: '키즈 메뉴' },
  },
  {
    id: 'dine-bread-oven', name: '갓 구운 빵', category: '외식·메뉴',
    desc: '오븐에서 막 꺼낸 빵 트레이', accent: '#c08552',
    useCase: '베이커리·브레드 메뉴',
    scaffold: 'A tray of freshly baked bread just pulled from a deck oven, golden crusts crackling, a dusting of flour, warm oven glow and a little heat shimmer, rustic bakery setting. No people. The product sits on the tray edge. The upper third is the warm dark oven area. Warm, fresh-baked photography.',
    textStyle: 'Warm rustic typography in cream on the dark upper area, small uppercase label and a sturdy headline.',
    defaultTexts: { label: 'FRESH BAKED', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '오븐에서 막 나온', subtitle: '베이커리' },
  },
  {
    id: 'dine-bbq-table', name: '고기 굽는 테이블', category: '외식·메뉴',
    desc: '숯불 원형 그릴과 쌈 채소', accent: '#3d2c2e',
    useCase: '고깃집·구이 메뉴',
    scaffold: 'A round charcoal grill set into a restaurant table with marbled meat sizzling on the grate, glowing coals beneath, fresh lettuce and side dishes around it, warm smoky light. No people. The product sits beside the grill. The upper third is the dark smoky upper area. Hearty, Korean barbecue photography.',
    textStyle: 'Hearty bold typography in warm white on the dark upper area, small uppercase label and a heavy headline.',
    defaultTexts: { label: 'BBQ', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '숯불에 구워야 제맛', subtitle: '구이 메뉴' },
  },
  {
    id: 'dine-soup-cauldron', name: '가마솥 육수', category: '외식·메뉴',
    desc: '주방 가마솥에서 우러나는 육수', accent: '#6b4226',
    useCase: '국밥·탕 등 오래 끓인 국물 메뉴',
    scaffold: 'A large cast iron cauldron of broth simmering on a restaurant kitchen fire, thick steam billowing, a long wooden ladle resting on the rim, warm firelight and dim kitchen shadows. No people. The product sits on the counter in front. The upper third is dark space with rising steam. Deep, slow-cooked heritage photography.',
    textStyle: 'Deep heritage typography in cream on the dark upper area, small uppercase label and a sturdy headline.',
    defaultTexts: { label: 'SLOW COOKED', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '오래 끓여 깊은 맛', subtitle: '국물 메뉴' },
  },
  {
    id: 'dine-dessert-plating', name: '디저트 플레이팅', category: '외식·메뉴',
    desc: '점 소스와 꽃잎으로 꾸민 디저트 접시', accent: '#f3d5b5',
    useCase: '디저트 코스·플레이팅 메뉴',
    scaffold: 'A fine dining dessert plated on a wide white plate with delicate sauce dots, a quenelle of cream, edible petals and a crisp tuile, soft gallery-like light on a pale stone table. The product sits beside the plate. The upper third is plain pale stone. Elegant, artful dessert photography.',
    textStyle: 'Elegant artful typography in warm brown on the upper stone, small spaced label and a serif-feeling headline.',
    defaultTexts: { label: 'DESSERT', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '마지막 한 접시', subtitle: '디저트' },
  },
  {
    id: 'dine-takeout-spread', name: '포장 용기 탑다운', category: '외식·메뉴',
    desc: '채워 둔 포장 용기들을 위에서', accent: '#f6bd60',
    useCase: '포장·테이크아웃 메뉴',
    scaffold: 'A top-down spread of takeout containers filled with colorful dishes, lids set aside, wooden chopsticks and napkins, a kraft paper bag with no printing, bright clean daylight on a light table. The product sits among the containers. The upper band is bare light table. Convenient, appetizing takeout photography.',
    textStyle: 'Friendly bold typography in deep brown on the bare upper band, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'TAKEOUT', title: '{productName}', subtitle: '{salePrice}' },
    sample: { title: '집에서도 그 맛', subtitle: '포장 메뉴' },
  },
  {
    id: 'dine-terrace-table', name: '야외 테이블', category: '외식·메뉴',
    desc: '햇살 드는 테라스 식탁', accent: '#a3b18a',
    useCase: '테라스·야외석 메뉴',
    scaffold: 'An outdoor restaurant table on a sunny terrace with a few shared plates, glasses of sparkling water, a small vase, dappled light through overhead leaves, a mild pleasant day. No people. The product sits on the table. The upper third is soft green leaves and light. Relaxed, open-air dining photography.',
    textStyle: 'Relaxed fresh typography in deep green on the soft upper leaves, small uppercase label and a light headline.',
    defaultTexts: { label: 'OPEN AIR', title: '{productName}', subtitle: '' },
    sample: { title: '바깥에서 먹는 한 끼', subtitle: '야외석 메뉴' },
  },

  // ══ 안내·예약 (13 · 행사 · 2026-10-04 신설) ══
  {
    id: 'event-notice-booking', name: '예약 오픈', category: '안내·예약', kind: 'event',
    desc: '리본 갈피가 꽂힌 빈 예약 노트', accent: '#7a8f6b',
    useCase: '예약 접수를 시작할 때',
    scaffold: 'An elegant reservation book lying open on a reception desk, crisp blank pages with no writing, a satin ribbon bookmark, a fountain pen beside it, soft morning light, a small vase at the edge. The upper third is the calm softly blurred wall behind the desk. Welcoming, orderly hospitality photography.',
    textStyle: 'Graceful typography in deep olive on the calm upper wall, small uppercase label and an elegant headline.',
    defaultTexts: { label: 'BOOKING OPEN', title: '예약 오픈', subtitle: '일정을 확인해주세요' },
    sample: { title: '예약을 받습니다', subtitle: '원하는 날을 골라 주세요' },
  },
  {
    id: 'event-notice-slots', name: '예약 가능 시간', category: '안내·예약', kind: 'event',
    desc: '칸이 채워지는 둥근 슬롯 그래픽', accent: '#f4a261',
    useCase: '남은 예약 자리를 알릴 때',
    scaffold: 'A flat graphic design composition: a neat grid of rounded pill-shaped slots in the lower two thirds, some filled with warm orange and some left as empty outlines, a clean off-white background, subtle soft shadows, no numbers or letters anywhere. The upper third is plain off-white. Modern, clear information graphic style.',
    textStyle: 'Bold modern typography in deep charcoal in the upper third, small uppercase label and a large clean headline.',
    defaultTexts: { label: 'TIME SLOTS', title: '예약 가능 시간', subtitle: '남은 자리를 확인해주세요' },
    sample: { title: '남은 자리 안내', subtitle: '빈칸이 곧 자리예요' },
  },
  {
    id: 'event-notice-today', name: '당일 예약', category: '안내·예약', kind: 'event',
    desc: '아침 해가 비치는 문 일러스트', accent: '#ffb703',
    useCase: '당일 예약이 가능할 때',
    scaffold: 'A bright flat illustration: an open doorway with a rising sun shining through it, warm rays spreading across a simple path, a few round shrubs, clean vector shapes in yellow, orange and teal, no outlines and no lettering. The upper third is a plain warm sky color. Cheerful, inviting editorial illustration style.',
    textStyle: 'Cheerful bold typography in deep navy on the plain upper sky, small label and a rounded heavy headline.',
    defaultTexts: { label: 'TODAY', title: '당일 예약', subtitle: '오늘 바로 가능합니다' },
    sample: { title: '오늘 바로 오세요', subtitle: '당일 예약 가능' },
  },
  {
    id: 'event-notice-reminder', name: '예약 확인 알림', category: '안내·예약', kind: 'event',
    desc: '반짝이는 3D 호출 벨', accent: '#e5989b',
    useCase: '예약 전날 확인을 부탁할 때',
    scaffold: 'A glossy 3D render of a reception service bell with a soft pink metallic finish on a rounded pedestal, small sparkle shapes around it, a smooth pastel background with soft global illumination and a gentle shadow. The upper third is plain pastel space. Cute, clean 3D illustration style with no text on any surface.',
    textStyle: 'Soft rounded typography in deep rose on the plain upper space, small label and a bubbly headline.',
    defaultTexts: { label: 'REMINDER', title: '예약 확인', subtitle: '방문 전날 다시 알려 드려요' },
    sample: { title: '내일 뵙겠습니다', subtitle: '예약 확인 안내' },
  },
  {
    id: 'event-notice-reschedule', name: '예약 변경 안내', category: '안내·예약', kind: 'event',
    desc: '종이로 오린 두 달력 칸과 화살표', accent: '#8ecae6',
    useCase: '예약 변경 방법을 알릴 때',
    scaffold: 'A paper-cut collage: two blank square paper calendar pages with no numbers, one slightly faded and one bright, connected by a curved paper arrow, layered with soft shadows on a light blue paper background, a few small paper confetti pieces. The upper third is plain paper. Handmade, friendly paper craft style.',
    textStyle: 'Friendly crafted typography in deep blue on the plain upper paper, small label and a medium headline.',
    defaultTexts: { label: 'RESCHEDULE', title: '예약 변경', subtitle: '변경은 이렇게 해주세요' },
    sample: { title: '날짜를 바꾸고 싶다면', subtitle: '예약 변경 안내' },
  },
  {
    id: 'event-notice-pickup', name: '포장·배달 시작', category: '안내·예약', kind: 'event',
    desc: '픽업을 기다리는 종이봉투들', accent: '#e09f3e',
    useCase: '포장·배달 서비스를 새로 시작할 때',
    scaffold: 'A row of neatly folded paper takeout bags with no printing lined up on a counter ready for pickup, each sealed with a plain sticker, warm cozy shop light, a service bell on the counter. The upper third is the plain shop wall. Friendly, convenient takeout photography.',
    textStyle: 'Friendly bold typography in deep brown on the upper wall, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'TAKEOUT', title: '포장·배달 시작', subtitle: '이제 가져가실 수 있어요' },
    sample: { title: '이제 포장돼요', subtitle: '배달도 시작합니다' },
  },
  {
    id: 'event-notice-menu', name: '새 메뉴판 안내', category: '안내·예약', kind: 'event',
    desc: '도형이 새로 자리 잡는 그래픽', accent: '#e76f51',
    useCase: '메뉴·서비스 구성이 바뀔 때',
    scaffold: 'A bold graphic composition: simple geometric shapes such as circles, squares and half circles in warm orange, mustard and teal rearranging into a new orderly grid, faint motion trails showing their old positions, flat colors on a cream background, no letters or numbers. The upper third is plain cream. Modern Bauhaus-inspired graphic style.',
    textStyle: 'Strong geometric typography in deep charcoal set large in the upper third, small uppercase label and a bold headline.',
    defaultTexts: { label: 'RENEWED', title: '메뉴 개편', subtitle: '새 구성을 확인해주세요' },
    sample: { title: '메뉴가 새로워졌어요', subtitle: '바뀐 구성 안내' },
  },
  {
    id: 'event-notice-petok', name: '반려동물 동반', category: '안내·예약', kind: 'event',
    desc: '강아지 한 마리를 그린 선 일러스트', accent: '#90be6d',
    useCase: '반려동물 동반 입장을 알릴 때',
    scaffold: 'A minimal continuous line drawing of a happy dog sitting at a shop doorway with a water bowl beside it, a single-weight dark green line on a warm off-white background, a few soft color fills, plenty of empty space. The upper third is plain off-white. Charming, minimal line art style with no lettering.',
    textStyle: 'Friendly rounded typography in deep green in the upper third, small label and a warm medium headline.',
    defaultTexts: { label: 'PETS WELCOME', title: '반려동물 동반 가능', subtitle: '함께 들어오세요' },
    sample: { title: '같이 들어오세요', subtitle: '반려동물 환영' },
  },
  {
    id: 'event-notice-soldout', name: '품절 안내', category: '안내·예약', kind: 'event',
    desc: '빈 단상과 꽃 한 송이', accent: '#c9ada7',
    useCase: '품절을 알리고 양해를 구할 때',
    scaffold: 'An empty display pedestal in a softly lit room, a single flower lying on it beside a small folded card that is blank, gentle warm light, a sincere and apologetic mood. The upper third is the calm plain wall. Quiet, respectful notice photography.',
    textStyle: 'Gentle sincere typography in deep mauve on the upper wall, small uppercase label and a soft headline.',
    defaultTexts: { label: 'SOLD OUT', title: '품절 안내', subtitle: '다시 준비하고 있어요' },
    sample: { title: '모두 품절되었어요', subtitle: '기다려 주셔서 고맙습니다' },
  },
  {
    id: 'event-notice-payment', name: '결제 수단 추가', category: '안내·예약', kind: 'event',
    desc: '계산대 위 결제 단말기와 휴대폰', accent: '#3a86ff',
    useCase: '새 결제 방법을 알릴 때',
    scaffold: 'A clean checkout counter with a slim card terminal and a smartphone lying beside it, both screens dark and blank, a small plant and a paper bag with no printing, bright modern retail light. The upper third is the plain wall behind the counter. Convenient, modern payment photography.',
    textStyle: 'Modern clean typography in deep blue on the upper wall, small uppercase label and a crisp headline.',
    defaultTexts: { label: 'NEW PAYMENT', title: '결제 방법 추가', subtitle: '더 편하게 결제하세요' },
    sample: { title: '이렇게도 결제돼요', subtitle: '새 결제 방법' },
  },
  {
    id: 'event-notice-shipping', name: '배송 마감 시각', category: '안내·예약', kind: 'event',
    desc: '저녁 물류창고를 떠나는 트럭 판화', accent: '#264653',
    useCase: '당일 배송 마감 시각을 알릴 때',
    scaffold: 'A woodcut print illustration of a delivery truck leaving a warehouse at dusk, stacked parcels on a loading dock, bold carved lines, two-color ink in deep teal and warm orange on cream paper, visible wood grain texture, no lettering on the truck or boxes. The upper third is plain dusk sky in flat ink. Handmade printmaking style.',
    textStyle: 'Strong printmaking-style typography in deep teal on the plain upper sky, small label and a sturdy headline.',
    defaultTexts: { label: 'SHIPPING', title: '배송 마감 안내', subtitle: '마감 시각 전에 주문해주세요' },
    sample: { title: '오늘 보내 드려요', subtitle: '배송 마감 시각' },
  },
  {
    id: 'event-notice-return', name: '교환·반품 안내', category: '안내·예약', kind: 'event',
    desc: '다시 돌아가는 화살표를 단 3D 상자', accent: '#a5a58d',
    useCase: '교환·반품 방법을 안내할 때',
    scaffold: 'A clean 3D render of a rounded cardboard box with its lid open and a curved arrow shape looping back into it, a soft sage background, matte materials, gentle shadows, a roll of tape beside it, no printing or letters. The upper third is plain sage space. Simple, reassuring 3D illustration style.',
    textStyle: 'Clear helpful typography in deep olive on the plain upper space, small uppercase label and a medium headline.',
    defaultTexts: { label: 'RETURNS', title: '교환·반품 안내', subtitle: '방법을 확인해주세요' },
    sample: { title: '바꾸고 싶을 때는', subtitle: '교환·반품 방법' },
  },
  {
    id: 'event-notice-phone', name: '전화 상담', category: '안내·예약', kind: 'event',
    desc: '책상 위 헤드셋과 빈 메모지', accent: '#4f6d7a',
    useCase: '전화 상담·고객센터 운영을 알릴 때',
    scaffold: 'A tidy support desk: a headset resting beside a blank notepad and a pen, a cup of water, a small plant, soft bright office light, a softly blurred window behind. The upper third is the blurred bright window. Friendly, reliable customer care photography with no screens showing content.',
    textStyle: 'Friendly clear typography in deep teal over the bright upper area, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'CALL US', title: '전화 상담', subtitle: '운영 시간을 확인해주세요' },
    sample: { title: '전화로 물어보세요', subtitle: '친절하게 답해 드려요' },
  },

  // ══ 모집·참여 (13 · 행사 · 2026-10-04 신설) ══
  {
    id: 'event-join-testers', name: '체험단 모집', category: '모집·참여', kind: 'event',
    desc: '빈 카드와 샘플 상자가 놓인 테이블', accent: '#f28482',
    useCase: '체험단·제품 테스터를 모집할 때',
    scaffold: 'A bright table laid out with small sample boxes with no printing, blank cards and pens set at several places, waiting for testers to arrive, soft daylight, a tidy and inviting arrangement. No people. The upper third is the plain bright wall. Inviting, participatory photography.',
    textStyle: 'Inviting bold typography in deep coral on the upper wall, small uppercase label and a rounded headline.',
    defaultTexts: { label: 'TESTERS WANTED', title: '체험단 모집', subtitle: '먼저 써 보실 분을 찾아요' },
    sample: { title: '먼저 써 보실 분', subtitle: '체험단 모집' },
  },
  {
    id: 'event-join-supporters', name: '서포터즈 모집', category: '모집·참여', kind: 'event',
    desc: '빈 이름표와 목걸이 줄이 놓인 테이블', accent: '#4361ee',
    useCase: '서포터즈·홍보단을 모집할 때',
    scaffold: 'A row of blank name badges on colorful lanyards laid neatly on a table, a stack of plain notebooks and pens, bright energetic light, a sense of a team about to form. No people. The upper third is the plain wall. Energetic, team-spirited photography with no writing on the badges.',
    textStyle: 'Energetic typography in deep blue on the upper wall, small uppercase label and a bold headline.',
    defaultTexts: { label: 'JOIN US', title: '서포터즈 모집', subtitle: '함께할 분을 찾아요' },
    sample: { title: '함께 알릴 분 찾아요', subtitle: '서포터즈 모집' },
  },
  {
    id: 'event-join-photo', name: '사진 공모전', category: '모집·참여', kind: 'event',
    desc: '빈 액자가 걸린 갤러리 벽', accent: '#2b2d42',
    useCase: '사진·그림 공모전을 열 때',
    scaffold: 'A gallery wall with several empty frames of different sizes waiting to be filled, each lit by a small spotlight, a polished wooden floor, a quiet white gallery space. The upper third is the plain wall above the frames. Anticipatory, creative contest photography.',
    textStyle: 'Refined gallery typography in charcoal on the upper wall, small uppercase label and an elegant headline.',
    defaultTexts: { label: 'PHOTO CONTEST', title: '사진 공모전', subtitle: '당신의 한 장을 보내주세요' },
    sample: { title: '빈 액자를 채워 주세요', subtitle: '사진 공모전' },
  },
  {
    id: 'event-join-story', name: '사연 공모', category: '모집·참여', kind: 'event',
    desc: '우편함에서 쏟아지는 종이 봉투', accent: '#ef8354',
    useCase: '고객 사연·이야기를 모을 때',
    scaffold: 'A paper-cut collage of a cheerful mailbox overflowing with many little paper envelopes tumbling out, layered colored paper with soft shadows, warm orange and cream tones, small paper hearts among the envelopes, no writing on any envelope. The upper third is plain warm paper. Heartwarming, handmade paper craft style.',
    textStyle: 'Warm crafted typography in deep red brown on the plain upper paper, small label and a friendly headline.',
    defaultTexts: { label: 'YOUR STORY', title: '사연 공모', subtitle: '이야기를 들려주세요' },
    sample: { title: '이야기를 보내주세요', subtitle: '사연 공모' },
  },
  {
    id: 'event-join-naming', name: '이름 공모', category: '모집·참여', kind: 'event',
    desc: '빈 말풍선이 떠 있는 일러스트', accent: '#ffd166',
    useCase: '신제품·캐릭터 이름을 공모할 때',
    scaffold: 'A bright flat illustration of a large empty speech bubble floating at the middle of the frame above a small round pedestal at the bottom, little sparkles and stars around it, clean vector shapes in yellow, coral and navy, no outlines, nothing written inside the bubble. The upper third is a plain light background. Playful, inviting editorial illustration style.',
    textStyle: 'Playful bold typography in deep navy in the upper third, small label and a rounded headline.',
    defaultTexts: { label: 'NAME IT', title: '이름 공모', subtitle: '좋은 이름을 지어주세요' },
    sample: { title: '이름을 지어 주세요', subtitle: '이름 공모전' },
  },
  {
    id: 'event-join-vote', name: '둘 중 하나 투표', category: '모집·참여', kind: 'event',
    desc: '마주 선 두 색 단상의 대결 구도', accent: '#8338ec',
    useCase: '두 가지 중 하나를 고르는 투표',
    scaffold: 'A bold graphic composition split into two halves of contrasting color, violet on the left and orange on the right, each half holding an identical empty pedestal facing the other, a lightning-shaped divider between them, flat colors and clean shapes, no letters. The upper third is plain color across both halves. Energetic, competitive graphic poster style.',
    textStyle: 'Punchy bold typography in white across the upper third, small label and a heavy headline.',
    defaultTexts: { label: 'VOTE', title: '투표 이벤트', subtitle: '하나만 골라주세요' },
    sample: { title: '둘 중 하나만 골라요', subtitle: '투표 이벤트' },
  },
  {
    id: 'event-join-models', name: '모델 모집', category: '모집·참여', kind: 'event',
    desc: '조명이 켜진 빈 촬영 스튜디오', accent: '#adb5bd',
    useCase: '촬영 모델·참여자를 모집할 때',
    scaffold: 'An empty photo studio ready for a shoot: a seamless paper backdrop, two softbox lights switched on, a stool waiting in the center, a camera on a tripod in the foreground slightly blurred. No people. The upper third is the plain backdrop. Professional, inviting casting photography.',
    textStyle: 'Clean editorial typography in charcoal on the upper backdrop, small uppercase label and a bold headline.',
    defaultTexts: { label: 'CASTING', title: '모델 모집', subtitle: '촬영에 함께해 주세요' },
    sample: { title: '이 자리의 주인공', subtitle: '모델 모집' },
  },
  {
    id: 'event-join-staff', name: '직원 채용', category: '모집·참여', kind: 'event',
    desc: '빈 이름표가 달린 앞치마가 걸린 벽', accent: '#6a994e',
    useCase: '매장 직원·함께 일할 사람을 뽑을 때',
    scaffold: 'A clean apron hanging on a wall hook at mid height in a cozy shop backroom, a blank name tag pinned on it, a shelf with neat supplies, warm welcoming light. No people. The upper third is the plain wall above the hook. Friendly, sincere hiring photography.',
    textStyle: 'Warm sincere typography in deep green on the upper wall, small uppercase label and a medium headline.',
    defaultTexts: { label: 'WE ARE HIRING', title: '함께 일할 분', subtitle: '지원 방법을 확인해주세요' },
    sample: { title: '함께 일할 분을 찾아요', subtitle: '직원 채용' },
  },
  {
    id: 'event-join-recipe', name: '레시피 공모', category: '모집·참여', kind: 'event',
    desc: '수채로 그린 조리 도구와 재료', accent: '#e9c46a',
    useCase: '레시피·활용법 공모를 열 때',
    scaffold: 'A loose watercolor illustration of kitchen tools and ingredients scattered across the lower part of a page: a whisk, a wooden spoon, eggs, herbs and a mixing bowl, soft pigment blooms and paper texture, a warm yellow and green palette, no writing. The upper third is plain paper with a light wash. Charming hand-painted illustration style.',
    textStyle: 'Friendly hand-crafted feeling typography in deep brown on the upper paper, small label and a rounded headline.',
    defaultTexts: { label: 'RECIPE', title: '레시피 공모', subtitle: '나만의 방법을 알려주세요' },
    sample: { title: '나만의 레시피 공모', subtitle: '맛있는 방법을 모아요' },
  },
  {
    id: 'event-join-video', name: '후기 영상 공모', category: '모집·참여', kind: 'event',
    desc: '재생 버튼과 필름 띠의 그래픽', accent: '#ff6b6b',
    useCase: '사용 후기 영상·짧은 영상을 모을 때',
    scaffold: 'A punchy flat graphic of an oversized rounded play-button triangle inside a rounded rectangle frame, a strip of film sprocket holes running along the bottom edge, coral, black and warm white color blocks, a few motion lines, no letters or numbers. The play frame sits in the lower two thirds. The upper third is plain warm white. Energetic social video poster style.',
    textStyle: 'Playful bold typography in deep red on the soft upper area, small label and a bouncy headline.',
    defaultTexts: { label: 'SHORT VIDEO', title: '후기 영상 공모', subtitle: '짧은 영상을 보내주세요' },
    sample: { title: '찍어서 보내 주세요', subtitle: '후기 영상 공모' },
  },
  {
    id: 'event-join-ideas', name: '아이디어 모집', category: '모집·참여', kind: 'event',
    desc: '여러 전구 중 하나만 켜진 그래픽', accent: '#ffbe0b',
    useCase: '고객 아이디어·제안을 모을 때',
    scaffold: 'A flat graphic pattern of simple light bulb shapes arranged in a neat grid across the lower two thirds on deep navy, all outlined in pale gray except one glowing bright yellow with soft radiating lines, clean vector style, no letters. The upper third is plain deep navy. Smart, clear graphic poster style.',
    textStyle: 'Bright clean typography in warm yellow on the plain navy upper third, small label and a bold headline.',
    defaultTexts: { label: 'IDEAS', title: '아이디어 모집', subtitle: '생각을 나눠주세요' },
    sample: { title: '반짝 떠오른 생각', subtitle: '아이디어 모집' },
  },
  {
    id: 'event-join-ambassador', name: '앰배서더 모집', category: '모집·참여', kind: 'event',
    desc: '같은 의자 줄 가운데 빛나는 하나', accent: '#f9c74f',
    useCase: '브랜드 앰배서더·대표 고객을 뽑을 때',
    scaffold: 'A row of identical simple chairs in a clean white room, the one in the middle painted bright yellow and lit by a soft spotlight, gentle shadows, editorial calm. No people. The upper third is the plain white wall. Distinctive, aspirational editorial photography.',
    textStyle: 'Confident editorial typography in charcoal on the upper wall, small uppercase label and a bold headline.',
    defaultTexts: { label: 'AMBASSADOR', title: '앰배서더 모집', subtitle: '브랜드의 얼굴을 찾아요' },
    sample: { title: '우리를 대표할 분', subtitle: '앰배서더 모집' },
  },
  {
    id: 'event-join-mission', name: '참여 미션', category: '모집·참여', kind: 'event',
    desc: '말과 길이 그려진 보드게임 판', accent: '#48cae4',
    useCase: '단계별 참여 미션 이벤트',
    scaffold: 'A cheerful flat illustration of a board game path winding across the lower two thirds with colorful tiles, little game pieces, a pair of dice showing only dots, a finish flag with no writing, clean vector shapes in aqua, coral and yellow. The upper third is a plain light background. Playful, game-like editorial illustration style.',
    textStyle: 'Playful bold typography in deep navy in the upper third, small label and a bouncy headline.',
    defaultTexts: { label: 'MISSION', title: '참여 미션', subtitle: '한 칸씩 도전해보세요' },
    sample: { title: '한 칸씩 도전해요', subtitle: '참여 미션' },
  },
];
