/**
 * ★ 2026-09-05 AI 영업 아웃리치 : 샘플 예시 seed(코드 내장 · 마스킹본 · 폴백)
 * 출처 = 직원 실물 DM 10건 · 이메일 9건(2026-08-25~09-02). 브랜드명·상품명(본문 포함)·혜택 수치·링크·연락처·날짜는 〔〕로 가려져 있다.
 * 마스킹 = 운영 CT sales-outreach-exemplar-mask(순수)와 같은 규칙(0905(2) 재생성 · 상품명 본문 누수 정정). 재생성 = scratch/proto/rebuild-seed.ts(폐기 전제).
 * 용도 = 구성·리듬·문장 길이·톤의 참고(few-shot). 문장을 베끼는 용도가 아니다(프롬프트 규칙이 5어절 이상 차용을 금지).
 * 서빙 = DB 실물 예시(best_copy_assets kind=outreach_example · 베스트 구성에서 올린다)가 앞, 이 seed는 뒤(폴백). 선택·병합 = sales-outreach-exemplars.ts.
 */
export const OUTREACH_EXEMPLAR_SEED: Record<string, readonly string[]> = {
  "DM:fashion": [
    "[예시 · DM · fashion]\n  1. header\n  2. coupon\n    discount_label: 첫 구매 전용\n  3. product_carousel\n    title: 회원님을 위한 추천 상품\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    (… 외 2)\n  4. cta\n    label: 도작 보장 상품 보러 가기\n  5. product_carousel\n    title: 오늘 출발 상품\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    (… 외 2)\n  6. gallery\n  7. cta\n    label: 말랑이 · 쫀득빵 초대박 〔혜택〕 대전!\n  8. gallery\n    title: 균일가에 〔혜택〕 혜택 더하기!\n  9. cta\n    label: 초특가 라스트 찬스\n  10. countdown\n    urgency_text: 곧 모든 특가가 종료돼요!\n  11. footer",
    "[예시 · DM · fashion]\n  1. header\n  2. hero\n    headline: 오직 〔브랜드〕에서만\n    sub_copy: 유즈드 페스티벌 최대 〔혜택〕 일리윤 3일 혜택 / 〔브랜드〕 FW 26\n  3. slideshow\n    (… 외 1)\n  4. cta\n    label: 새로운 시즌을 위한 준비. 〔브랜드〕 바로가기*\n  5. gallery\n    title: 급상승 랭킹*\n    caption: 〔상품〕\n    caption: 〔상품〕\n    caption: 〔상품〕\n    caption: 〔상품〕\n    (… 외 2)\n  6. countdown\n    urgency_text: 〔브랜드〕 유즈드 페스티벌 〔혜택〕\n  7. youtube_embed\n  8. gallery\n    title: 과즙세연 추천템*\n    caption: 〔상품〕\n    caption: 〔상품〕\n    caption: 〔상품〕\n  9. promo_code\n    description: 인플루언서 추천템 〔혜택〕코드\n    instructions: 결제 시 코드 입력 〔혜택〕 즉시〔혜택〕\n  10. instagram_embed",
    "[예시 · DM · fashion]\n  1. header\n  2. hero\n    headline: 〔상품〕 팬츠\n    sub_copy: 자연스럽게 살아나는 입체적인 〔상품〕핏 팬츠를 소개합니다. 〔상품〕 컬렉션을 지금 바로 만나보세요.\n  3. slideshow\n    (… 외 1)\n  4. product_carousel\n    title: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  5. product_carousel\n    title: 〔상품〕\n    name: 〔상품〕\n  6. product_carousel\n    title: 〔상품〕\n    name: 〔상품〕\n  7. gallery\n  8. cta\n    label: 회원만 받는 어텀위크 혜택\n  9. gallery\n  10. footer",
    "[예시 · DM · fashion]\n  1. header\n  2. youtube_embed\n  3. hero\n    headline: 〔상품〕\n    sub_copy: 1년에 단 1번 진행되는 기회*\n  4. product_carousel\n    title: WOMEN\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    (… 외 2)\n  5. product_carousel\n    title: MEN\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    (… 외 2)\n  6. coupon\n    discount_label: 추가 〔혜택〕\n    usage_condition: 온라인몰 한정 이벤트\n  7. countdown\n    urgency_text: 베스트 특별〔혜택〕\n  8. slideshow\n  9. cta\n    label: COMING SOON 상품 보러가기\n  10. gallery\n    title: 〔브랜드〕 Week\n    caption: 〔상품〕\n  11. gallery\n    title: 세상을 바꾸는 옷의 힘\n    caption: 〔상품〕\n  12. store_info",
    "[예시 · DM · fashion]\n  1. header\n  2. slideshow\n    (… 외 1)\n  3. product_carousel\n    title: 당신을 위한 추천 아이템\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    (… 외 2)\n  4. tab_cards\n    label: 〔브랜드〕 라이브\n    content: 슈펜 f/w 신상 라이브 한정 특가 〔링크〕 브랜드 라이브 특가 〔링크〕 모렌트 x 최실장 가을 니트 라이브 특가 〔링크〕\n  5. youtube_embed\n  6. countdown\n    urgency_text: 라이브 특가 끝나기까지\n  7. product_carousel\n    title: 직진배송 아이템\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  8. cta\n    label: 사이트 바로가기\n  9. sns"
  ],
  "DM:beauty": [
    "[예시 · DM · beauty]\n  1. header\n  2. hero\n    headline: 단 3일간의 강력한 멤버십 혜택\n    sub_copy: 등급별 〔혜택〕&올리브포인트 〔혜택〕\n  3. cta\n    label: 올리브 데이 혜택 보러 가기\n  4. product_carousel\n    title: 요즘 주목 받는 상품\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    (… 외 2)\n  5. product_carousel\n    title: 나를 위한 추천 상품\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    (… 외 2)\n  6. gallery\n    title: Weekly Special\n    caption: 〔상품〕\n  7. gallery\n  8. cta\n    label: 8월 〔브랜드〕신상위크 기획전\n  9. countdown\n    urgency_text: 〔브랜드〕 세일\n  10. footer",
    "[예시 · DM · beauty]\n  1. header\n  2. video\n  3. countdown\n    urgency_text: 샤쉐 3종 놓치기까지!\n  4. product_carousel\n    title: 모공 사냥 완료! 빈틈없이 매끈한 피부♡\n    name: 〔상품〕\n  5. reviews\n    title: 정말 모공이 줄어들까?* 찐 후기를 확인하세요!\n    body: 지성 피부인데 끈적임 없이 수분만 가득 채워주고 모공이 쫀쫀해지는 느낌이라 너무 좋아요!\n    body: 바르자마자 느껴지는 쿨링감으로 열감은 내리고 모공은 쫀쫀하게! 이거 바르고 메이크업 하면 깐달걀 피부 그냥 완성될 것 같아요\n    body: 피부결이 매끈해지면서 모공이 확실히 덜 부각돼 보여요 피부가 쫀쫀해지고 화장 끼임도 덜해진 것 같아요 다 쓰면 무조건 재구매할 거에요\n    body: 수분감이 좋아서 기초 단계에서 편하게 바르기 딱이에요! 무엇보다 신기한게 바르고 나면 옅은 모공들이 살짝 정돈되는 느낌이라 피부결이 훨씬 깔끔해 보셔요\n  6. gallery\n  7. tab_cards\n    label: STEP.1\n    content: 〔상품〕 각질과 모공 속 노폐물 제거 당김 없이 촉촉한 클레이 모공팩\n    label: STEP.2\n    content: 〔상품〕 붓기는 쏙* 모공은 꽉 조이는 타이트닝* 세럼\n  8. product_carousel\n    title: 다이어트 루틴 STEP.1 같이 담기!\n    name: 〔상품〕\n  9. text_card\n    tag: BEST ITEM\n    body: 나를 위한 선택. best 상품 구경하기\n    headline: 〔브랜드〕 품절 대란템\n  10. slideshow\n    caption: 〔상품〕\n    caption: 〔상품〕\n    caption: 〔상품〕\n    caption: 〔상품〕\n    (… 외 1)\n  11. instant_coupon\n    coupon_label: 〔브랜드〕 고객님들을 위한 혜택\n    usage_instructions: 결제시 중복 〔혜택〕\n    discount_description: 알림받기 동의 고객 상품중복〔혜택〕\n  12. footer",
    "[예시 · DM · beauty]\n  1. header\n  2. hero\n    headline: 나를 가꾸는 나만의 컬러\n    sub_copy: *나만의 색을 찾다. 〔상품〕\n  3. product_carousel\n    title: _ 〔상품〕 new products\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  4. youtube_embed\n  5. cta\n    label: BEST-SELLER 바로가기\n  6. slideshow\n  7. text_card\n    tag: 〔상품〕 익스피리언스 존\n    body: 완벽한 색상을 발견하고, 다양한 스타일을 실험하며, 구매 전에 자신만의 완벽한 메이크업 조합을 찾으세요.\n    headline: 당신의 진정한 색깔이 기다리고 있습니다\n  8. gallery\n    caption: 〔상품〕\n  9. slideshow\n  10. sns"
  ],
  "DM:commerce": [
    "[예시 · DM · commerce]\n  1. header\n  2. hero\n  3. cta\n    label: 썸머 뷰티쇼 보러 가기\n  4. product_carousel\n    title: 전품목 MEGA SALE\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  5. hero\n  6. product_carousel\n    title: 민감 피부 종결템\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  7. cta\n    label: 트러블엔 〔브랜드〕\n  8. cta\n    label: 베이스는 〔브랜드〕\n  9. cta\n    label: 〔브랜드〕 신상 출시\n  10. footer",
    "[예시 · DM · commerce]\n  1. header\n  2. hero\n    headline: 럭셔리 라이프 스타일을 위한 최고의 선택\n    sub_copy: 디자인부터 제조 까지 모든 단계에서 우리는 뛰어난 품질을 위해 세심한 기준을 목표로 삼고 있습니다. 브랜드의 핵심 가치는 고객들에게 지속적으로 최상의 경험을 제공하여, 럭셔리 라이프 스타일을 즐길 수 있는 기회를 선보이는 것입니다.\n  3. cta\n    label: 〔브랜드〕 바로 가기\n  4. gallery\n  5. product_carousel\n    name: 〔상품〕\n  6. cta\n    label: 〔상품〕 바로 가기\n  7. footer"
  ],
  "EMAIL:fashion": [
    "[예시 · EMAIL · fashion] 제목: 1년에 단 한 번의 행사\n  1. header\n  2. hero\n    headline: 1년에 단 한 번, 베스트상품 특별 이벤트\n    sub_copy: 가장 사랑받은 아이템들을 만나보세요\n  3. text_card\n    tag: 연 1회 특별전\n    body: 선선한 바람이 부는 가을, 〔브랜드〕가 1년에 한 번 준비하는 특별 이벤트를 시작합니다. 오래 곁에 두고 입는 아이템들을 이번 기회에 편하게 둘러보세요.\n    headline: 가장 많은 사랑을 받은 베스트 상품\n  4. product_carousel\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  5. coupon\n    discount_label: 베스트 상품 추가 〔혜택〕\n    usage_condition: 온라인몰 한정 이벤트\n  6. cta\n    label: 랭킹 제품 보러가기\n  7. text_card\n    body: 조만간 고객님 곁을 찾아갈 출시 예정 아이템을 보여드립니다. 선선하게 불어오는 가을의 바람을 기다리며, 미리 생각하고 장바구니에 담아두세요! 멋진 계절을 맞이할 나를 위한 선택*\n    headline: 출시 예정 신상품을 소개합니다.\n  8. gallery\n    title: COMING SOON 상품\n  9. cta\n    label: 신상품 보러가기\n  10. gallery\n    title: 2026 가을·겨울 컬렉션을 만나는 특별한 일주일.\n  11. gallery\n    title: 세상을 바꾸는 옷의 힘\n  12. store_info",
    "[예시 · EMAIL · fashion] 제목: FW26 신상부터 서머 슈즈까지, 지금 만나보세요\n  1. header\n  2. gallery\n    title: 오직 〔브랜드〕\n  3. hero\n    headline: 감각적인 스타일의 FW 26 신상\n    sub_copy: 정해진 길 밖으로 나만의 방식대로* # 〔브랜드〕\n  4. text_card\n    tag: Penfield\n    body: 많은 분들이 찾고 구매하고 있는 베스트 상품템 구경하러 가기 # 동궁 # 〔상품〕 판매 1만개 돌파중! # 한소희 PICK 〔브랜드〕 팬츠 한정판매중!\n    headline: 〔브랜드〕 랭킹 급상승\n  5. product_carousel\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  6. text_card\n    tag: 과즙세연 인플루언서 소장템\n    body: 처서가 지나가는 이 시점 인플루언서가 믿고 구매한 상품 따라사볼까? 훌쩍 다가온 차가운 바람에 미리 준비하는 가을 무드\n    headline: 올가을 인플루언스의 소장템을 믿고 구매하자!\n  7. product_carousel\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  8. coupon\n    discount_label: 인플루언서 〔혜택〕\n    usage_condition: 결제 시 추가 〔혜택〕 가능\n  9. cta\n    label: 〔브랜드〕 바로가기",
    "[예시 · EMAIL · fashion] 제목: 〔고객명〕님 당신을 위한 추천템, 지금 만나보세요\n  1. header\n  2. gallery\n    title: 〔브랜드〕 FW 〔혜택〕 추가 이벤트\n  3. text_card\n    tag: 초대장\n    body: 무더운 여름의 끝자락, 취향에 꼭 맞을 추천템을 〔브랜드〕에서 만나보세요.\n    headline: 〔고객명〕님만을 위한 추천템\n  4. product_carousel\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  5. text_card\n    tag: 직진배송\n    body: 지금 필요한 아이템, 오래 기다리지 않아도 괜찮아요. 밤 10시 전에 주문하시면 직진배송으로 빠르게 받아보실 수 있어요.\n    headline: 밤 10시 전 주문 시 직진배송\n  6. product_carousel\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  7. text_card\n    tag: 라이브 혜택\n    body: 오늘 라이브에서만 챙기실 수 있는 혜택을 준비했어요. 자세한 내용은 아래 사이트를 통해 확인해보세요.\n    headline: 라이브에서만 만나는 특별 〔혜택〕 이벤트\n  8. cta\n    label: 라이브 참여하기",
    "[예시 · EMAIL · fashion] 제목: 첫 구매 〔혜택〕\n  1. header\n  2. hero\n    headline: 첫 구매를 응원하는 작은 선물\n    sub_copy: 선선해진 가을, 〔브랜드〕에서 시작해보세요\n  3. text_card\n    tag: 첫 구매 전용 혜택\n    body: 〔브랜드〕를 처음 찾아주신 분들께 특별한 〔혜택〕 혜택을 준비했어요. 아래 〔혜택〕을 챙기고 마음에 드는 아이템을 편하게 골라보세요.\n    headline: 처음 오신 분들을 위한 〔혜택〕\n  4. coupon\n    discount_label: 첫 구매 전용 〔혜택〕\n  5. product_carousel\n    title: 지금 인기있는 추천 상품\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  6. text_card\n    tag: 기획전\n    body: 더블 〔혜택〕팩으로 준비했어요. 전 상품 〔혜택〕과 추가 〔혜택〕을 함께 챙겨 알차게 담아가세요. 자세한 혜택은 아래 버튼에서 확인해보세요.\n    headline: 균일가 페스타 · 라이프 아울렛\n  7. cta\n    label: 말랑이 초대박 〔혜택〕 대전!\n    label: 초특가 라스트 찬스\n  8. footer",
    "[예시 · EMAIL · fashion] 제목: 〔상품〕 팬츠\n  1. header\n  2. hero\n    sub_copy: 자연스럽게 살아나는 입체적인 〔상품〕핏 팬츠 〔상품〕 컬렉션을 지금 바로 만나보세요.\n  3. text_card\n    tag: NEW\n    body: 선선한 바람이 반가운 가을, 매일 입기 좋은 팬츠을 준비했어요.\n    headline: 커브가 살아있는 지금,\n  4. product_carousel\n    title: 이번 시즌 추천 팬츠\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  5. cta\n    label: 〔상품〕 팬츠 보러 가기\n  6. text_card\n    tag: AUTUMN WEEK\n    body: 회원전용 〔혜택〕, 룰렛 이벤트, 리뷰 이벤트, 시즌오프 세일까지. 어텀위크 기간 동안 매일 한번, 회원이면 누구나 참여 가능해요.\n    headline: 〔브랜드〕 어텀위크가 시작됐어요\n  7. cta\n    label: 어텀위크 이벤트 참여하기\n  8. gallery\n  9. footer"
  ],
  "EMAIL:beauty": [
    "[예시 · EMAIL · beauty] 제목: 〔브랜드〕 신상 위크\n  1. header\n  2. hero\n    headline: 8월 〔브랜드〕 신상 위크\n    sub_copy: 이번 달 새로 나온 신상, 한자리에 모았어요\n  3. text_card\n    tag: NEW ARRIVAL\n    body: 무더위에 지친 피부와 데일리 케어를 위한 8월 신상만 골라 담았어요. 화면으로 먼저 만나보시고, 마음에 드는 아이템 천천히 둘러보세요.\n    headline: 기다리셨죠, 이번 달 신상이에요\n  4. product_carousel\n    title: 〔상품〕 신상\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  5. text_card\n    tag: MEMBERSHIP\n    body: 이번 신상 위크는 단 3일간 진행돼요. 회원님께 먼저 살짝 알려드리는 소식이니 여유 있게 둘러보세요.\n    headline: 단 3일간의 멤버십 혜택\n  6. cta\n    label: 〔브랜드〕 신상 위크 GO\n  7. footer",
    "[예시 · EMAIL · beauty] 제목: 〔상품〕가 전하는 나만의 컬러 완성\n  1. header\n  2. hero\n    headline: 나를 가꾸는 나만의 컬러\n    sub_copy: 나만의 색을 찾다 〔상품〕*\n  3. product_carousel\n    title: _ 〔상품〕 new products\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  4. product_carousel\n    title: BEST 인기상품\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  5. text_card\n    tag: 〔상품〕 익스피리언스 존\n    body: 완벽한 색상을 발견하고, 다양한 스타일을 실험하며, 구매 전에 자신만의 완벽한 메이크업 조합을 찾으세요.\n    headline: 당신의 진정한 색깔이 기다리고 있습니다\n  6. cta\n    label: 사이트 바로가기",
    "[예시 · EMAIL · beauty] 제목: 〔고객명〕님께 조용히 건네는 〔상품〕 초대장\n  1. header\n  2. gallery\n  3. hero\n    headline: 모공사냥에 여러분을 초대합니다\n    sub_copy: 여름 끝, 〔상품〕을 채우는 세럼 한 병\n  4. text_card\n    tag: 고객님들의 찐 후기!\n    body: 붓기 쏙!* 모공 꽉!* 〔상품〕 스킨 다이어트 + 늘어진 모공 정조준! + 무결점 화잘먹 피부 수, 면적, 깊이까지 입체적으로 꿰뚫는 강력한 모공 사냥! 4주 사용으로 증명된 눈에 보이는 모공 타이트닝 효과를 만나보세요.\n    headline: 모공 사냥 세럼으로 4대 모공 고민 해결\n  5. text_card\n    tag: point 5가지\n    body: point 1. 방치된 붓기! 텐션 UP 어느각도에도 무결점 point 2. 느슨해진 모공을 탄탄하게! 펩타이드와 산뜻한 식물성 〔상품〕 시너지 point 3. 열 받고 열린 모공 즉각 쿨링* 확실한 타이트닝 point 4. 울퉁불퉁 모공을 조여 매끈한 화잘먹 피부 완성! point 5. 지복합성 피부도 안심하게 오일감은 빼고 수분감을 채운 논코네도제닉 포뮬러로 매일 매일 안심하고 사용 가능\n    headline: 비우고 조이는 모공 다이어트\n  6. product_carousel\n    title: 모공사냥에 찰떡궁합 담으러 가기!\n    name: 〔상품〕\n    name: 〔상품〕\n  7. cta\n    label: 〔브랜드〕 전제품 구경해보기"
  ],
  "EMAIL:commerce": [
    "[예시 · EMAIL · commerce] 제목: 썸머 뷰티쇼\n  1. header\n  2. hero\n    headline: 〔상품〕 썸머 뷰티쇼\n    sub_copy: 전품목 메가 세일!\n  3. cta\n    label: 썸머 뷰티쇼 보러 가기\n  4. text_card\n    tag: SUMMER BEAUTY SHOW\n    body: 한여름을 지나온 피부는 그 어느 때보다 진정과 회복이 필요해요. 〔상품〕 전 품목으로 지친 피부를 부드럽게 달래보세요.\n    headline: 더위에 지친 피부 긴급 케어\n  5. product_carousel\n    title: 썸머 뷰티쇼 추천 상품\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  6. text_card\n    tag: VACANCE BEST PICK\n    body: 여름의 끝자락, 남은 더위까지 산뜻하게 마무리해줄 아이템을 모았어요. 선케어부터 진정 마스크까지 여름 필수템으로 챙겨보세요.\n    headline: 바캉스 베스트 PICK\n  7. product_carousel\n    title: 바캉스 베스트 PICK\n    name: 〔상품〕\n    name: 〔상품〕\n    name: 〔상품〕\n  8. cta\n    label: 트러블엔 〔브랜드〕\n  9. cta\n    label: 베이스는 〔브랜드〕\n  10. cta\n    label: 〔브랜드〕 신상 출시\n  11. footer"
  ]
};
